# Blog info
blog_name: zhoushaw
slogan: Find the bug of the world
url: http://www.forsigner.com

# Set avatar (Absolute url and relative url)
avatar: https://s10.mogucdn.com/mlcdn/c45406/190317_10046af208g71l99jkg2cd2h3abaa_386x394.png

# Set favicon
favicon: https://s10.mogucdn.com/mlcdn/c45406/190317_10046af208g71l99jkg2cd2h3abaa_386x394.png

# For seo
keywords: forsigner,å‰ç«¯,è®¾è®¡,Hexoä¸»é¢˜,å‰ç«¯å¼€å‘,ç”¨æˆ·ä½“éªŒ,è®¾è®¡,frontend,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: Github
    url: https://github.com/zhoushaw
    target_blank: true
  - name: Project
    url: /project/
    target_blank: true #åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: Juejin
    url: https://juejin.im/user/5a91537df265da4e8700e73b
    target_blank: true

# config page nav
page_nav:
  - name: åšå®¢
    url: /archives/
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /categories/
    target_blank: false
  - name: æ ‡ç­¾
    url: /tags/
    target_blank: false
  # - name: å‹é“¾
  #   url: /link/
  #   target_blank: false
  - name: å…³äº
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: æœç´¢
    url: /search/
    target_blank: false # åœ¨æ–°é¡µé¢æ‰“å¼€

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: true # true|fase

# ç›’å­
toolbox:
  isShow: true # true|fase
  text: ç›’å­

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: äº¤æ¢å‹é“¾å¯ä»¥é‚®ä»¶ codingzx@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: æ‰«ä¸€æ‰«ï¼Œæ”¯æŒforsigner
  items:
    - type: å¾®ä¿¡
      text: å¾®ä¿¡æ‰«ä¸€æ‰«
      imgUrl: /images/qr-wechat.png
    - type: æ”¯ä»˜å®
      text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: /css/personal-style.css

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—èƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
home_background_scheme: light # darkã€light

# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================
# Stats
# google_analytics: UA-38189205-1
# baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service

# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#æœ‰è¨€ç”¨æˆ·ç¼–å·
# uyan_key:

# ç•…è¨€, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  changyan_appid:
  changyan_appkey:

# gitalkè¯„è®ºç»„ä»¶ï¼ŒæŠŠä¸‹é¢çš„é…ç½®æ¢æˆä½ çš„ï¼Œå®˜æ–¹æ–‡æ¡£: https://gitalk.github.io/
gitalk:
  enable: true # å¦‚æœä½¿ç”¨ gitalkï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  clientID: 277317290454635afa73
  clientSecret: 78223c859304da5e8d71bfce136d436c6ff95c37
  repo: blog-comment
  owner: forsigner
  admin: forsigner


# gitment comment service
gitment:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # å¦‚æœä½¿ç”¨valineï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# ä¸ç®—å­,æ–‡ç« è®¿é—®é‡ç»Ÿè®¡å’Œæ˜¾ç¤º
busuanzi: true

# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "zhoushaw, 1995."
    - "å–œæ¬¢è®¾è®¡ï¼Œæ“…é•¿ç¼–ç¨‹ï¼Œå–œæ¬¢ç¡æ‡’è§‰."
    - "å‰ç«¯å¼€å‘å·¥ç¨‹å¸ˆï¼Œå¸¸ç”¨ JavaScript / Node / Electron."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@zhoushaw"
    text_value_url: https://github.com/zhoushaw
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "codingzx@gmail.com"
  - type: location
    icon: icon-location
    text_value: æ­å·

# link:
#   - name: ç»‡ç½‘
#     info: èº«ä½“å’Œçµé­‚ï¼Œæ€»æœ‰ä¸€ä¸ªåœ¨è·¯ä¸Š
#     url: http://zheng-ji.info/
#     avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
#   - name: Dongyado
#     info: ç”Ÿå‘½ä¸æ­¢ï¼ŒæŠ˜è…¾ä¸æ¯
#     url: http://dongyado.com/
#     avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
#   - name: OrangeCoder
#     info: android ffmpeg nodejs gradle
#     url: http://orangecoder.com/
#     avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
#   - name: EverET
#     info: å¥½è®°æ€§ä¸å¦‚çƒ‚ç¬”å¤´
#     url: http://everet.org/about-me/
#     avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
#   - name: é¢˜å¶
#     info: FP, GUI, Writing
#     url: http://tiye.me/
#     avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
#   - name: McChen
#     info: Stay Hungry, Stay Foolish
#     url: http://mcchen.club/
#     avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: Instagram
    url: https://github.com/zhoushaw/Instagram
    intro: A web-app with some feature like Instagram!!ğŸ˜‰ğŸ“¸ğŸ˜Š
  # - type: personal
  #   name: web-fontmin
  #   url: https://github.com/forsigner/web-fontmin
  #   intro: å­—ä½“å­é›†åŒ–ï¼Œåœ¨çº¿æå–ä½ éœ€è¦çš„å­—ä½“

# Online contact 
daovoice: true
daovoice_app_id: b89c9b48  #è¿™é‡Œè¾“å…¥è·å–çš„app_id



# å­—æ•°ç»Ÿè®¡ã€é˜…è¯»æ—¶é•¿
# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  enable: true
  item_text: true
  wordcount: true         # å•ç¯‡ å­—æ•°ç»Ÿè®¡
  min2read: true          # å•ç¯‡ é˜…è¯»æ—¶é•¿
  totalcount: false       # ç½‘ç«™ å­—æ•°ç»Ÿè®¡
  separated_meta: true
